"""create curriculum import tables

Revision ID: f1ceeacfa405
Revises: 69643d000e12
Create Date: 2026-07-11 16:00:34.940896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1ceeacfa405'
down_revision: Union[str, Sequence[str], None] = '69643d000e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', name='import_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('total_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_import_jobs_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs')),
    sa.UniqueConstraint('file_hash', name='uq_import_jobs_file_hash')
    )
    op.create_index(op.f('ix_import_jobs_created_by_id'), 'import_jobs', ['created_by_id'], unique=False)
    op.create_index('ix_import_jobs_status_created', 'import_jobs', ['status', 'created_at'], unique=False)
    op.create_table('curriculum_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_import_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_import_id'], ['import_jobs.id'], name=op.f('fk_curriculum_content_source_import_id_import_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_content'))
    )
    op.create_index(op.f('ix_curriculum_content_external_id'), 'curriculum_content', ['external_id'], unique=True)
    op.create_index(op.f('ix_curriculum_content_topic'), 'curriculum_content', ['topic'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_job_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('raw_record', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], name=op.f('fk_import_errors_import_job_id_import_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_errors'))
    )
    op.create_index(op.f('ix_import_errors_import_job_id'), 'import_errors', ['import_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_errors_import_job_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_curriculum_content_topic'), table_name='curriculum_content')
    op.drop_index(op.f('ix_curriculum_content_external_id'), table_name='curriculum_content')
    op.drop_table('curriculum_content')
    op.drop_index('ix_import_jobs_status_created', table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_created_by_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
