"""create chat event consumers

Revision ID: fc5bfebc6f7e
Revises: f1ceeacfa405
Create Date: 2026-07-12 12:25:01.438314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5bfebc6f7e'
down_revision: Union[str, Sequence[str], None] = 'f1ceeacfa405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events')),
    sa.UniqueConstraint('interaction_id', name='uq_analytics_events_interaction_id')
    )
    op.create_table('compliance_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_events')),
    sa.UniqueConstraint('interaction_id', name='uq_compliance_events_interaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
